dist: trusty
sudo: false
language: erlang
otp_release:
  - 19.2
  - 20.3
  - 21.3
  - 22.0
install:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3
  - export PATH=$PWD:$PATH
script:
  - ./ci
cache:
  directories:
    - .plt
