---
name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: Run checks and tests over ${{matrix.otp_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    container:
      image: erlang:${{matrix.otp_vsn}}
    strategy:
      matrix:
        otp_vsn: ["21.3", "22.3", "23.2"]
        os: [ubuntu-latest]
    steps:
      - name: Install Git 2.18
        shell: bash
        run: |
          apt-get update
          apt-get -y install tcl tcl-dev gettext
          cd /usr/src/
          wget https://github.com/git/git/archive/v2.18.0.tar.gz -O git.tar.gz
          tar -xf git.tar.gz
          cd git-*
          make prefix=/usr/local all
          make prefix=/usr/local install
          cd $HOME
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Environment versions
        shell: bash
        run: |
          rebar3 --version
          erl -version
      - shell: bash
        run: rebar3 dialyzer
      - shell: bash
        run: rebar3 ct --suite=git_SUITE
      - shell: bash
        run: rebar3 cover
      - shell: bash
        run: rebar3 escriptize && _build/default/bin/elvis rock
