---
name: build
on: [push, pull_request]
jobs:
  ci:
    name: Run checks and tests over ${{matrix.otp_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        otp_vsn: [23, 24, 25]
        os: [ubuntu-20.04]
    steps:
      - name: Install Git 2.18
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get -y install tcl tcl-dev gettext libcurl4-openssl-dev
          cd /usr/src/
          sudo wget https://github.com/git/git/archive/v2.18.0.tar.gz -O git.tar.gz
          sudo tar -xf git.tar.gz
          cd git-*
          sudo make prefix=/usr/local all
          sudo make prefix=/usr/local install
          cd $HOME
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        id: setup-beam
        with:
          otp-version: ${{matrix.otp_vsn}}
          rebar3-version: '3.20'
      - shell: bash
        run: rebar3 dialyzer
      - shell: bash
        run: rebar3 ct --suite=git_SUITE
      - shell: bash
        run: rebar3 cover
      - shell: bash
        run: rebar3 escriptize && _build/default/bin/elvis rock
